WebSite_Galgnvegl/WebSite_Galgnvegl/Controllers/OfferController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebSite_Galgnvegl.Controllers
{
    public class OfferController : Controller
    {
        //
        // GET: /Offer/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult OfferIndex()
        {
            ViewBag.Message = "Unser Angebot:";
            return View();
        }

        public ActionResult Camp()
        {
            ViewBag.Message = "Camp";
            return View();
        }

        public ActionResult ChainsOfFaith()
        {
            ViewBag.Message = "ChainsOfFaith";
            return View();
        }

        public ActionResult LiselottesGewandung()
        {
            ViewBag.Message = "LiselottesGewandung";
            return View();
        }

        public ActionResult MedivalManufactoring()
        {
            ViewBag.Message = "MedivalManufactoring";
            return View();
        }

        public ActionResult Workshop()
        {
            ViewBag.Message = "Workshop";
            return View();
        }

        public ActionResult Theater()
        {
            ViewBag.Message = "Theater";
            return View();
        }

    }
}

WebSite_Galgnvegl/WebSite_Galgnvegl/Views/Offer/Camp.cshtml
@{
    ViewBag.Title = "Camp";

    @section featured {
        <section class="featured">
            <div class="content-wrapper">
                <hgroup class="title">
                    <h1>@ViewBag.Message</h1>
                </hgroup>
                <p>
                    Textteil
                    <nav class="content-wrapper">
                        @Html.ActionLink("zurück", "OfferIndex", "Offer")<br />
                    </nav>
                </p>
            </div>
        </section>
    }

WebSite_Galgnvegl/WebSite_Galgnvegl/Views/Offer/ChainsOfFaith.cshtml
@{
    ViewBag.Title = "ChainsOfFaith";
}

    @section featured {
        <section class="featured">
            <div class="content-wrapper">
                <hgroup class="title">
                    <h1>@ViewBag.Message</h1>
                </hgroup>
                <p>
                    Textteil
                    <nav class="content-wrapper">
                        @Html.ActionLink("zurück", "OfferIndex", "Offer")<br />
                    </nav>
                </p>
            </div>
        </section>
    }

WebSite_Galgnvegl/WebSite_Galgnvegl/Views/Offer/LiselottesGewandung.cshtml
@{
    ViewBag.Title = "LiselottesGewandung";
}

    @section featured {
        <section class="featured">
            <div class="content-wrapper">
                <hgroup class="title">
                    <h1>@ViewBag.Message</h1>
                </hgroup>
                <p>
                    Textteil
                    <nav class="content-wrapper">
                        @Html.ActionLink("zurück", "OfferIndex", "Offer")<br />
                    </nav>
                </p>
            </div>
        </section>
    }

WebSite_Galgnvegl/WebSite_Galgnvegl/Views/Offer/MedivalManufactoring.cshtml
@{
    ViewBag.Title = "MedivalManufactoring";
}

    @section featured {
        <section class="featured">
            <div class="content-wrapper">
                <hgroup class="title">
                    <h1>@ViewBag.Message</h1>
                </hgroup>                
                <p>

                    <nav class="menu2" , style="margin-right: 50px">
                        Die Spinnerey
                    </nav>
                    Die wohl bekannteste Art, Stoffe herzustellen besteht darin, Schafe zuscheren, und die Wolle zu spinnen.
                    Auf Wunsch zeigt Liselotte wie im mittelalter mit der Handspindel Wolle hergestellt wurde.
                    Dabei wird Rohwolle zunächst gewaschen, gegebenenfalls gefärbt und anschließend kardiert. 
                    Beim Kardieren werden wie Wollfasern in eine Richtung gekämmt, wodurch das spätere Spinnen erleichtert wird.
                    Sind die Rohwollfasern gleichmäßig in eine Richtung ausgerichtet, spricht man von einem Wollflies, aus dem dann der Faden gesponnen wird.
                    Mehrere Wollfäden werden zum schluss zu einem Garn verzwirnt und anschließen am Webstuhl zu Stoffen verwebt.
                    <br />
                    <br />
                    Gern dürfen sich Marktbesucher zu mir gesellen und sich an diesem alten Handwerk versuchen. 
                    Ich erkläre die einzelnen Schritte und führe das spinnen gerne vor.
                    Ich spinne seit August 2015 mit der Handyspindel, seit Dezember 2015 am Spinnrad. (Liselotte von Zellrudndorff)
                    <br />
                    <br />

                    <nav class="menu2", style="margin-right: 50px">
                        Die Näherey
                    </nav>
                    Mittelalterliche Kleidung wuchs nicht einfach auf Bäumen, sondern musste in langwieriger Handarbeit 


                    
                    <nav class="content-wrapper">
                        @Html.ActionLink("zurück", "OfferIndex", "Offer")<br />
                    </nav>
                </p>
            </div>
        </section>
    }

WebSite_Galgnvegl/WebSite_Galgnvegl/Views/Offer/OfferIndex.cshtml
@{
    ViewBag.Title = "OfferIndex";
}

    @section featured {
        <section class="featured">
            <div class="content-wrapper">
                <hgroup class="title">
                    <h1>@ViewBag.Message</h1>
                </hgroup>
                <p>
                    <nav class="content-wrapper">
                        <span class="menu2" style="margin-right:50px">
                            @Html.ActionLink("Camp", "Camp", "Offer")<br />
                        </span>
                        <span class="menu2" style="margin-right:50px">
                            @Html.ActionLink("Chains of Faith", "ChainsOfFaith", "Offer")<br />
                        </span>
                        <span class="menu2" style="margin-right:50px">
                            @Html.ActionLink("Liselottes Gewandung", "LiselottesGewandung", "Offer")<br />
                        </span>
                        <span class="menu2" style="margin-right:50px">
                            @Html.ActionLink("Medival Manufactoring", "MedivalManufactoring", "Offer")<br />
                        </span>
                        <span class="menu2" style="margin-right:50px">
                            @Html.ActionLink("Workshop", "Workshop", "Offer")<br />
                        </span>
                        <span class="menu2" style="margin-right:50px">
                            @Html.ActionLink("Theater", "Theater", "Offer")<br />
                        </span>
                        <span class="menu2" style="margin-right:50px">
                            <a href="http://www.brimborium.org/">Brimborium</a><br />
                        </span>
                        @Html.ActionLink("zurück", "Index", "Home")<br/>
                    </nav>
                </p>
            </div>
        </section>
    }

WebSite_Galgnvegl/WebSite_Galgnvegl/Views/Offer/Theater.cshtml
@{
    ViewBag.Title = "Theater";
}
    @section featured {
        <section class="featured">
            <div class="content-wrapper">
                <hgroup class="title">
                    <h1>@ViewBag.Message</h1>
                </hgroup>
                <p>
                    Textteil
                    <nav class="content-wrapper">
                        @Html.ActionLink("zurück", "OfferIndex", "Offer")<br />
                    </nav>
                </p>
            </div>
        </section>
    }

WebSite_Galgnvegl/WebSite_Galgnvegl/Views/Offer/Workshop.cshtml
@{
    ViewBag.Title = "Workshop";
}

    @section featured {
        <section class="featured">
            <div class="content-wrapper">
                <hgroup class="title">
                    <h1>@ViewBag.Message</h1>
                </hgroup>
                <p>
                    Textteil
                    <nav class="content-wrapper">
                        @Html.ActionLink("zurück", "OfferIndex", "Offer")<br />
                    </nav>
                </p>
            </div>
        </section>
    }