WebSite_Galgnvegl/WebSite_Galgnvegl/Controllers/AboutUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebSite_Galgnvegl.Controllers
{
    public class AboutUsController : Controller
    {
        //
        // GET: /AboutUs/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AboutUsIndex()
        {
            ViewBag.Message = "Das sind wir:";
            return View();
        }
        
        public ActionResult IgorWorjaz()
        {
            ViewBag.Message = "Igor Worjaz";
            return View();
        }

        public ActionResult SteapaSnotor()
        {
            ViewBag.Message = "Steapa Snotor";
            return View();
        }

        public ActionResult LiselotteVonZellrudndorff()
        {
            ViewBag.Message = "Liselotte von Zellrudndorff";
            return View();
        }

        public ActionResult LamiaDieSanfte()
        {
            ViewBag.Message = "Lamia die Sanfte";
            return View();
        }

        public ActionResult SimonDerFeurige()
        {
            ViewBag.Message = "Simon der Feurige";
            return View();
        }

        public ActionResult Grygr()
        {
            ViewBag.Message = "Grygr";
            return View();
        }

        public ActionResult PaterJudas()
        {
            ViewBag.Message = "Pater Judas";
            return View();
        }

    }
}

WebSite_Galgnvegl/WebSite_Galgnvegl/Views/AboutUs/AboutUsIndex.cshtml
@{
    ViewBag.Title = "AboutUsIndex";
}

    @section featured {
        <section class="featured">
            <div class="content-wrapper">
                <hgroup class="title">
                    <h1>@ViewBag.Message</h1>
                </hgroup>
                <p>
                    <nav class="content-wrapper">
                        <nav class="content-wrapper1">
                            <span class="menu2" style="margin-right:50px">
                                @Html.ActionLink("Igor Worjaz", "IgorWorjaz", "AboutUs")<br />
                            </span>
                            <br />
                            <span class="menu2" style="margin-right:50px">
                                @Html.ActionLink("Steapa Snotor", "SteapaSnotor", "AboutUs")<br />
                            </span>
                            <br />
                            <span class="menu2" style="margin-right:50px">
                                @Html.ActionLink("Liselotte von Zellrudndorff", "LiselotteVonZellrudndorff", "AboutUs")<br />
                            </span>
                            <br />
                            <span class="menu2" style="margin-right:50px">
                                @Html.ActionLink("Lamia die Sanfte", "LamiaDieSanfte", "AboutUs")<br />
                            </span>
                            <br />
                            <span class="menu2" style="margin-right:50px">
                                @Html.ActionLink("Simon", "Simon", "AboutUs")<br />
                            </span>
                            <br />
                            <span class="menu2" style="margin-right:50px">
                                @Html.ActionLink("Grygr", "Grygr", "AboutUs")<br />
                            </span>
                            <br />
                            <span class="menu2" style="margin-right:50px">
                                @Html.ActionLink("Pater Judas", "PaterJudas", "AboutUs")<br />
                            </span>
                            <br />
                            @Html.ActionLink("zurück", "Index", "Home")<br />
                        </nav>

                    </nav>
                </p>
            </div>
        </section>
    }

WebSite_Galgnvegl/WebSite_Galgnvegl/Views/AboutUs/Grygr.cshtml
@{
    ViewBag.Title = "Grygr";
}
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="utf-8">
    <title>
        @ViewBag.Message;
    </title>
</head>
<body>
    @section featured {
        <section class="featured">
            <div class="content-wrapper">
                <hgroup class="title">
                    <h1>@ViewBag.Message</h1>
                </hgroup>
                <p>
                    ich bin Grygr
                    <nav class="content-wrapper">
                        @Html.ActionLink("zurück", "AboutUsIndex", "AboutUs")<br />
                    </nav>
                </p>
            </div>
        </section>
    }
</body>
</html>
<script type="text/javascript">

</script>

WebSite_Galgnvegl/WebSite_Galgnvegl/Views/AboutUs/IgorWorjaz.cshtml
@{
    ViewBag.Title = "IgorWorjaz";
}
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="utf-8">
    <title>
        @ViewBag.Message;
    </title>
</head>
<body>
    @section featured {
        <section class="featured">
            <div class="content-wrapper">
                <hgroup class="title">
                    <h1>@ViewBag.Message</h1>
                </hgroup>
                <p>
                    ich bin Igor
                    <nav class="content-wrapper">
                        @Html.ActionLink("zurück", "AboutUsIndex", "AboutUs")<br />
                    </nav>
                </p>
            </div>
        </section>
    }
</body>
</html>
<script type="text/javascript">

</script>

WebSite_Galgnvegl/WebSite_Galgnvegl/Views/AboutUs/LamiaDieSanfte.cshtml
@{
    ViewBag.Title = "LamiaDieSanfte";
}
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="utf-8">
    <title>
        @ViewBag.Message;
    </title>
</head>
<body>
    @section featured {
        <section class="featured">
            <div class="content-wrapper">
                <hgroup class="title">
                    <h1>@ViewBag.Message</h1>
                </hgroup>
                <p>
                    ich bin Lamia
                    <nav class="content-wrapper">
                        @Html.ActionLink("zurück", "AboutUsIndex", "AboutUs")<br />
                    </nav>
                </p>
            </div>
        </section>
    }
</body>
</html>
<script type="text/javascript">

</script>

WebSite_Galgnvegl/WebSite_Galgnvegl/Views/AboutUs/LiselotteVonZellrudndorff.cshtml
@{
    ViewBag.Title = "LiselotteVonZellrudndorff";
}
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="utf-8">
    <title>
        @ViewBag.Message;
    </title>
</head>
<body>
    @section featured {
        <section class="featured">
            <div class="content-wrapper">
                <hgroup class="title">
                    <h1>@ViewBag.Message</h1>
                </hgroup>
                <p>
                    Mein Name ist Liselotte von Zellrudndurff. In dem kleinen thüringischen Zellrudndurff wurde ich mit einem bürgerlichen Namen geboren. Mit der Aussicht auf eine gute Heirat zog ich in Begleitung die Stadt.
                    Doch mein Unglück war vorprogrammiert.  Um mir die Zeit zu vertreiben, begann ich Kleidung zu nähen und auf dem städtischen Markt feil zu bieten. So gelang es mir, obwohl meine Familie nicht wohlhabend ist, ein wenig Geld anzusparen.
                    <br />Aber es dauerte nicht lange, bis Neid in mein Umfeld einzog. Schon nach wenigen Wochen wurde ich der Hexerei bezichtigt. Wie es üblich war, holten die Büttel mich ab und brachten mich in den Kerker.
                    Ich denke nicht gern an diese Zeit zurück. Es gibt in der Stadt zwei Henker Steapa Snotor und Igor Worjaz. Während der eine daran Arbeitet mir ein Geständnis abzuringen, verarztet Igor Worjaz meinen von der Befragung zerschundenen Körper.
                    Auch wenn ich jede Schuld von mir wies, vollzog der Henker eine Hexenprobe. Ich weiß nicht, wie ich das überlebt habe, aber die Tatsache, dass ich es tat, reichte aus, um mich der Hexerei zu überführen.<br />
                    Nur wenige Stunden später wurde ich auf den Scheiterhaufen geführt. Entgegen ihrer üblichen Arbeitsweise stand Igor Worjaz und nicht Steapa Snotor vor mir am Scheiterhaufen.
                    Ich wurde am Pfahl festgebunden und kurz bevor der Scheiterhaufen enzündet wurde, wandte sich Igor an den Ratsherrn. Wir waren uns in der Zeit im Kerker näher gekommen, und jetzt wollte er von seinem Recht als Henker gebrauch machen.
                    Mit dem Einverständnis des obersten Ratsherrn und der Verurteilten ist es einem Henker erlaubt, eine zum Tode verurteilte Frau zu Heiraten. <br />
                    Ich stand also vor der Wahl, ob ich jetzt sterben wollte oder für den Rest meines Lebens als die Frau des Henkers, als Außgestoßene leben wollte. Die meisten Frauen würden den Tod wählen. Aber ich nicht. Ich wollte Leben.
                    <br /><br />
                    So bin ich ein Teil der Henkersfamilie geworden. Jetzt lebe ich als Ausgestoßene im Haus des Henkers und trage meinen Teil zum Familienunterhalt bei. Ich nähe Kleidung, die ich versuche auf dem Markt zu verkaufen.
                    Solche Verkäufe bringen leider nur wenig Geld ein, denn nur wenige Städter wollen Waren von den Henkern oder ihrer Familie kaufen, oder auch nur die eigenen Waren verkaufen.
                    <nav class="content-wrapper">
                        @Html.ActionLink("zurück", "AboutUsIndex", "AboutUs")<br />
                    </nav>
                </p>
            </div>
        </section>
    }
</body>
</html>
<script type="text/javascript">

</script>

WebSite_Galgnvegl/WebSite_Galgnvegl/Views/AboutUs/PaterJudas.cshtml
@{
    ViewBag.Title = "PaterJudas";
}
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="utf-8">
    <title>
        @ViewBag.Message;
    </title>
</head>
<body>
    @section featured {
        <section class="featured">
            <div class="content-wrapper">
                <hgroup class="title">
                    <h1>@ViewBag.Message</h1>
                </hgroup>
                <p>
                    Der noch junge und naive Wanderprediger Judas entdeckte sehr früh seine Liebe zu Gott. Als
                    dritter Sohn einer Bauernfamilie stand er durch das tägliche Gebet schon von Geburt an in
                    Verbindung zum christlichen Glauben.
                    <br /> Seine aufgeweckte und neugierige Art trieb ihn nach
                    der Arbeit auf dem Feld immer wieder in die Kirche, wo er den Gottesdiensten beiwohnte, die
                    ansässigen Geistlichen mit Fragen überschüttete und sich letztendlich selbst, gegen den
                    Willen seines Vaters, der Kirche anschloss um dem Weg Gottes zu folgen. Schon während
                    seiner Lehre als Mönch bewies er Eifer und Selbstständigkeit. Da er in ärmlichen
                    Verhältnissen aufwuchs, war ein Leben in Askese war für ihn nie ein Problem. Nur mit seiner
                    Kutte bedeckt; seiner Bibel unter dem Arm und seinem Kreuz am Hals wuchs er im Kloster
                    zu einem jungen Mann heran, welcher stets Selbstlos und Hilfsbereit seinen Ordensbrüdern
                    und dem Volk Gottes zu diensten stand. Sein besonderes Interesse galt vor allem der
                    Bekehrung von Ungläubigen, aber auch an der Jagd auf Hexen beteiligte er sich ein ums
                    andere mal. Mit seinem Sakrament endete auch sein Leben bei seinen Glaubensbrüdern.
                    Getrieben von Eifer verlies er schon bald sein Kloster und seinen Orden um den Glauben
                    Gottes in die Welt zu tragen. Er erlebte auf seinen Wegen allerhand Abenteuer, begegnete
                    düsteren Gestalten und Ungläubigen, Gleichgesinnten und verlorenen Seelen.
                    So trug es sich zu, dass Judas eines Tages auf eine kleine Gruppe stieß. Die Galgenvegl zu
                    Chemnitz. Ein scheinbar bunt durcheinander gewürfelter Haufen aus Henkern, einer Hexe,
                    einer Dirne und anderen seltsamen anmutenden Gestalten. Für Judas war dies eine völlig neue
                    Erfahrung. Nachdem sie einige Zeit einen gemeinsamen Weg teilten, beschloss Judas sich der
                    Gruppe anzuschließen um all den Seelen der Verurteilten, welchen sie auf ihren Reisen
                    begegneten, beizustehen und auf dem Weg zu Gott zu begleiten.
                    <nav class="content-wrapper">
                        @Html.ActionLink("zurück", "AboutUsIndex", "AboutUs")<br />
                    </nav>
                </p>
            </div>
        </section>
    }
</body>
</html>
<script type="text/javascript">

</script>

WebSite_Galgnvegl/WebSite_Galgnvegl/Views/AboutUs/SimonDerFeurige.cshtml
@{
    ViewBag.Title = "Simon der Feurige";
}
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="utf-8">
    <title>
        @ViewBag.Message;
    </title>
</head>
<body>
    @section featured {
        <section class="featured">
            <div class="content-wrapper">
                <hgroup class="title">
                    <h1>@ViewBag.Message</h1>
                </hgroup>
                <p>
                    ich bin Simon
                    <nav class="content-wrapper">
                        @Html.ActionLink("zurück", "AboutUsIndex", "AboutUs")<br />
                    </nav>
                </p>
            </div>
        </section>
    }
</body>
</html>
<script type="text/javascript">

</script>

WebSite_Galgnvegl/WebSite_Galgnvegl/Views/AboutUs/SteapaSnotor.cshtml
@{
    ViewBag.Title = "SteapaSnotor";
}
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="utf-8">
    <title>
        @ViewBag.Message;
    </title>
</head>
<body>
    @section featured {
        <section class="featured">
            <div class="content-wrapper">
                <hgroup class="title">
                    <h1>@ViewBag.Message</h1>
                </hgroup>
                <p>
                    ich bin Steapa
                    <nav class="content-wrapper">
                        @Html.ActionLink("zurück", "AboutUsIndex", "AboutUs")<br />
                    </nav>
                </p>
            </div>
        </section>
    }
</body>
</html>
<script type="text/javascript">

</script>